'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CM0011
    Public Property mbnumi As Integer
    Public Property mb_manumi As Nullable(Of Integer)
    Public Property mbcodvendedor As Nullable(Of Integer)
    Public Property mbest As Nullable(Of Integer)
    Public Property mbfact As Nullable(Of Date)
    Public Property mbhact As String
    Public Property mbuact As String

End Class
