'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CM001
    Public Property manumi As Integer
    Public Property mamesa As Nullable(Of Integer)
    Public Property macodrepart As Nullable(Of Integer)
    Public Property maest As Nullable(Of Integer)
    Public Property mafact As Nullable(Of Date)
    Public Property mahact As String
    Public Property mauact As String

End Class
