'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB001
    Public Property banumi As Integer
    Public Property banum As Nullable(Of Integer)
    Public Property baproc As String
    Public Property balinea As Nullable(Of Integer)
    Public Property bamensaje As String
    Public Property batipo As Nullable(Of Integer)
    Public Property bafact As Nullable(Of Date)
    Public Property bahact As String
    Public Property bauact As String

End Class
