'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC002
    Public Property cbnumi As Integer
    Public Property cbdesc As String
    Public Property cbdirec As String
    Public Property cbtelef As String
    Public Property cbcat As Nullable(Of Integer)
    Public Property cbsal As Nullable(Of Decimal)
    Public Property cbci As String
    Public Property cbobs As String
    Public Property cbfnac As Nullable(Of Date)
    Public Property cbfing As Nullable(Of Date)
    Public Property cbfret As Nullable(Of Date)
    Public Property cbfot As String
    Public Property cbest As Nullable(Of Boolean)
    Public Property cbeciv As String
    Public Property cbplan As Nullable(Of Integer)
    Public Property cbreloj As Nullable(Of Integer)
    Public Property cbfact As Nullable(Of Date)
    Public Property cbhact As String
    Public Property cbuact As String

End Class
