'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC0041
    Public Property chnumi As Integer
    Public Property chfec As Nullable(Of Date)
    Public Property chcod As String
    Public Property chdesc As String
    Public Property chtmov As Nullable(Of Integer)
    Public Property chnrem As Nullable(Of Integer)
    Public Property chcan As Nullable(Of Double)
    Public Property chmonbs As Nullable(Of Double)
    Public Property chmonsus As Nullable(Of Double)
    Public Property chnota As Nullable(Of Integer)
    Public Property chlin As Integer
    Public Property chobs As String
    Public Property chfact As Nullable(Of Date)
    Public Property chhact As String
    Public Property chuact As String

End Class
