'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC0011
    Public Property cicod As String
    Public Property cilin As Nullable(Of Integer)
    Public Property cinserie As String
    Public Property cieserie As Nullable(Of Boolean)
    Public Property ciest As Nullable(Of Boolean)

End Class
