'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC006
    Public Property cfid As Integer
    Public Property cfdesc As String
    Public Property cffact As Nullable(Of Date)
    Public Property cfhact As String
    Public Property cfuact As String

End Class
