'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC004B
    Public Property ccbnumi As Integer
    Public Property ccbzona As Nullable(Of Integer)
    Public Property ccbtcre As Nullable(Of Integer)

End Class
