'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC0012
    Public Property cpnumi As Integer
    Public Property cptc1 As Nullable(Of Integer)
    Public Property cpcprod As Nullable(Of Integer)

End Class
