'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC0051
    Public Property ceId As Integer
    Public Property cecon As Nullable(Of Integer)
    Public Property cenum As Nullable(Of Integer)
    Public Property cedesc As String
    Public Property cefact As Nullable(Of Date)
    Public Property cehact As String
    Public Property ceuact As String

End Class
