'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC005
    Public Property cdId As Integer
    Public Property cdcon As Nullable(Of Integer)
    Public Property cddesc As String
    Public Property cdver As Nullable(Of Boolean)
    Public Property cdfact As Nullable(Of Date)
    Public Property cdhact As String
    Public Property cduact As String

End Class
