'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC003
    Public Property chnumi As Integer
    Public Property chcprod As String
    Public Property chcatcl As Nullable(Of Integer)
    Public Property chprecio As Nullable(Of Decimal)
    Public Property chfact As Nullable(Of Date)
    Public Property chhact As String
    Public Property chuact As String

End Class
