'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC004A2
    Public Property ccabnumi As Integer
    Public Property ccabtc4anumi As Nullable(Of Integer)
    Public Property ccabprod As Nullable(Of Integer)
    Public Property ccabcant As Nullable(Of Decimal)

End Class
