'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC0091
    Public Property clnumi As Nullable(Of Integer)
    Public Property clcodu As Nullable(Of Integer)
    Public Property clshow As Nullable(Of Boolean)
    Public Property cllin As Integer
    Public Property clcopy As Nullable(Of Boolean)

End Class
