'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC0111
    Public Property coline As Integer
    Public Property conumi As Nullable(Of Integer)
    Public Property coing1 As String
    Public Property cosal1 As String
    Public Property coing2 As String
    Public Property cosal2 As String

End Class
