'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TCA001
    Public Property caanumi As Integer
    Public Property caafdoc As Nullable(Of Date)
    Public Property caaprov As Nullable(Of Integer)
    Public Property caanfac As String
    Public Property caaobs As String
    Public Property caafact As Nullable(Of Date)
    Public Property caahact As String
    Public Property caauact As String
    Public Property caatven As Nullable(Of Integer)
    Public Property caafvcred As Nullable(Of Date)
    Public Property caamon As Nullable(Of Integer)
    Public Property caaest As Nullable(Of Integer)
    Public Property caadesc As Nullable(Of Decimal)
    Public Property caadescpro1 As Nullable(Of Decimal)
    Public Property caadescpro2 As Nullable(Of Decimal)
    Public Property caadesctot As Nullable(Of Decimal)
    Public Property caatotal As Nullable(Of Decimal)
    Public Property caaemision As Nullable(Of Integer)
    Public Property caaconsigna As Nullable(Of Integer)
    Public Property caaretenc As Nullable(Of Integer)
    Public Property caaasientoi As Nullable(Of Integer)
    Public Property caaffactura As Nullable(Of Date)

End Class
