'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TCP0011
    Public Property cpbnumi As Nullable(Of Integer)
    Public Property cpbfdoc As Nullable(Of Date)
    Public Property cpbmonto As Nullable(Of Decimal)
    Public Property cpblin As Integer
    Public Property cpbfact As Nullable(Of Date)
    Public Property cpbhact As String
    Public Property cpbuact As String

End Class
