'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TD001
    Public Property danumi As Integer
    Public Property dacanumi As Nullable(Of Integer)
    Public Property dacant1 As Nullable(Of Integer)
    Public Property dacant2 As Nullable(Of Integer)
    Public Property dapreciou As Nullable(Of Decimal)
    Public Property dafinicio As Nullable(Of Date)
    Public Property daffin As Nullable(Of Date)
    Public Property daestado As Nullable(Of Integer)
    Public Property dafact As Nullable(Of Date)
    Public Property dahact As String
    Public Property dauact As String

End Class
