'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TFC001
    Public Property fcanumi As Integer
    Public Property fcafdoc As Nullable(Of Date)
    Public Property fcanit As String
    Public Property fcarsocial As String
    Public Property fcanfac As Nullable(Of Long)
    Public Property fcandui As Nullable(Of Integer)
    Public Property fcaautoriz As Nullable(Of Long)
    Public Property fcaitc As Nullable(Of Decimal)
    Public Property fcanscf As Nullable(Of Decimal)
    Public Property fcasubtotal As Nullable(Of Decimal)
    Public Property fcadesc As Nullable(Of Decimal)
    Public Property fcaibcf As Nullable(Of Decimal)
    Public Property fcacfiscal As Nullable(Of Decimal)
    Public Property fcaccont As String
    Public Property fcatcom As Nullable(Of Integer)
    Public Property fcanumito11 As Nullable(Of Integer)

End Class
