'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TI0052
    Public Property iiid As Integer
    Public Property iiigid As Nullable(Of Integer)
    Public Property iicodpro As Nullable(Of Integer)
    Public Property iicant As Nullable(Of Integer)
    Public Property iitotcant As Nullable(Of Integer)
    Public Property iipcosto As Nullable(Of Decimal)
    Public Property iifact As Nullable(Of Date)
    Public Property iihact As String
    Public Property iiuact As String

End Class
