'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TI0051
    Public Property ihid As Integer
    Public Property ihigid As Nullable(Of Integer)
    Public Property ihcodpro As Nullable(Of Integer)
    Public Property ihcant As Nullable(Of Integer)
    Public Property ihtotcant As Nullable(Of Integer)
    Public Property ihpcosto As Nullable(Of Decimal)
    Public Property ihfact As Nullable(Of Date)
    Public Property ihhact As String
    Public Property ihuact As String

End Class
