'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TI005
    Public Property igid As Integer
    Public Property igfdoc As Nullable(Of Date)
    Public Property igobs As String
    Public Property igcodpack As Nullable(Of Integer)
    Public Property igcantP As Nullable(Of Integer)
    Public Property igpcosto As Nullable(Of Decimal)
    Public Property igcantNP As Nullable(Of Integer)
    Public Property igfechaNP As Nullable(Of Date)
    Public Property igest As Nullable(Of Integer)
    Public Property igalm As Nullable(Of Integer)
    Public Property igfact As Nullable(Of Date)
    Public Property ighact As String
    Public Property iguact As String

End Class
