'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TI0041
    Public Property ifid As Integer
    Public Property ifieid As Nullable(Of Integer)
    Public Property ifcli As Nullable(Of Integer)
    Public Property ifmon As Nullable(Of Decimal)

End Class
