'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TI004
    Public Property ieid As Integer
    Public Property iefdoc As Nullable(Of Date)
    Public Property ieconcep As Nullable(Of Integer)
    Public Property ieobs As String
    Public Property ietip As Nullable(Of Integer)
    Public Property ieidcab As Nullable(Of Integer)
    Public Property ieiddet As Nullable(Of Integer)
    Public Property iefact As Nullable(Of Date)
    Public Property iehact As String
    Public Property ieuact As String

End Class
