'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TL001
    Public Property lanumi As Integer
    Public Property lacity As Nullable(Of Integer)
    Public Property laprovi As Nullable(Of Integer)
    Public Property lazona As Nullable(Of Integer)
    Public Property lacolor As String
    Public Property lafact As Nullable(Of Date)
    Public Property lahact As String
    Public Property lauact As String

End Class
