'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TL002
    Public Property ldnumi As Integer
    Public Property ldchof As Nullable(Of Integer)
    Public Property ldfec As Nullable(Of Date)
    Public Property ldhora As String
    Public Property lblat As Nullable(Of Decimal)
    Public Property lblongi As Nullable(Of Decimal)

End Class
