'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TM001
    Public Property ibid As Integer
    Public Property ibfdoc As Nullable(Of Date)
    Public Property ibconcep As Nullable(Of Integer)
    Public Property ibobs As String
    Public Property ibest As Nullable(Of Integer)
    Public Property ibalm As Nullable(Of Integer)
    Public Property ibiddc As Nullable(Of Integer)
    Public Property ibidchof As Nullable(Of Integer)
    Public Property ibidvent As Nullable(Of Integer)
    Public Property ibidconcil As Nullable(Of Integer)
    Public Property ibfact As Nullable(Of Date)
    Public Property ibhact As String
    Public Property ibuact As String

End Class
