'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TM0012
    Public Property ieid As Integer
    Public Property ieconcti2 As Nullable(Of Integer)
    Public Property ieest As Nullable(Of Integer)

End Class
