'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO002
    Public Property odnumi As Integer
    Public Property odnota As Nullable(Of Integer)
    Public Property odfdoc As Nullable(Of Date)
    Public Property odtprod As Nullable(Of Integer)
    Public Property odrepa As Nullable(Of Integer)
    Public Property odtap As Nullable(Of Integer)
    Public Property oddes As Nullable(Of Double)
    Public Property odfact As Nullable(Of Date)
    Public Property odhact As String
    Public Property oduact As String

End Class
