'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0021
    Public Property oenumi As Integer
    Public Property oelin As Nullable(Of Integer)
    Public Property oencli As Nullable(Of Integer)
    Public Property oeefec As Nullable(Of Decimal)
    Public Property oecred As Nullable(Of Decimal)
    Public Property oenrec As String
    Public Property oenfac As String
    Public Property oenped As Nullable(Of Integer)
    Public Property oetipo As String

End Class
