'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0022
    Public Property ofnumi As Nullable(Of Integer)
    Public Property oflin As Nullable(Of Integer)
    Public Property ofccli As Nullable(Of Integer)
    Public Property ofcprod As String
    Public Property ofcant As Nullable(Of Integer)
    Public Property ofcant2 As Nullable(Of Integer)
    Public Property ofest As Nullable(Of Integer)
    Public Property ofest2 As Nullable(Of Integer)
    Public Property ofid As Integer

End Class
