'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0051
    Public Property omnumi As Integer
    Public Property omolnumi As Integer
    Public Property omestado As Integer
    Public Property omTipoCam As Decimal
    Public Property omCorteD As Decimal
    Public Property omCantD As Decimal
    Public Property omTotalD As Decimal
    Public Property omCorteB As Decimal
    Public Property omCantB As Decimal
    Public Property omTotalB As Decimal

    Public Overridable Property TO005 As TO005

End Class
