'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0011
    Public Property obnumi As Integer
    Public Property obcprod As String
    Public Property obpcant As Nullable(Of Decimal)
    Public Property obpbase As Nullable(Of Decimal)
    Public Property obptot As Nullable(Of Decimal)
    Public Property obdesc As Nullable(Of Decimal)
    Public Property obtotal As Nullable(Of Decimal)
    Public Property obfamilia As Nullable(Of Integer)
    Public Property obcampo1 As Nullable(Of Integer)
    Public Property obcampo2 As Nullable(Of Decimal)

End Class
