'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0042
    Public Property ojnumi As Integer
    Public Property ojnumi2 As Nullable(Of Integer)
    Public Property ojccli As Nullable(Of Integer)
    Public Property ojnota As String
    Public Property ojobs As String
    Public Property ojprecon As Nullable(Of Decimal)
    Public Property ojprecre As Nullable(Of Decimal)
    Public Property ojdesc As Nullable(Of Decimal)

End Class
