'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0043
    Public Property oknumi As Integer
    Public Property oknumi2 As Nullable(Of Integer)
    Public Property okcprod As Nullable(Of Integer)
    Public Property okccant As Nullable(Of Decimal)
    Public Property okprecio As Nullable(Of Decimal)

End Class
