'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0014
    Public Property ofnumi As Integer
    Public Property ofnumiped As Integer
    Public Property ofest As Nullable(Of Integer)
    Public Property ofobs As String
    Public Property oftip As Nullable(Of Integer)
    Public Property ofconcep As Nullable(Of Integer)
    Public Property offact As Nullable(Of Date)
    Public Property ofhact As String
    Public Property ofuact As String

End Class
