'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO003
    Public Property ognumi As Integer
    Public Property ogrec As Nullable(Of Integer)
    Public Property ogfdoc As Nullable(Of Date)
    Public Property ogcli As Nullable(Of Integer)
    Public Property ogmon As Nullable(Of Decimal)
    Public Property ognota As Nullable(Of Integer)
    Public Property ogtprod As Nullable(Of Integer)
    Public Property ogfact As Nullable(Of Date)
    Public Property oghact As String
    Public Property oguact As String

End Class
