'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0041
    Public Property oinumi As Integer
    Public Property oinumi2 As Nullable(Of Integer)
    Public Property oicprod As Nullable(Of Integer)
    Public Property oivmovil As Nullable(Of Decimal)
    Public Property oisubtotal As Nullable(Of Decimal)
    Public Property oicant As Nullable(Of Decimal)

End Class
