'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO004
    Public Property ohnumi As Integer
    Public Property ohfec As Nullable(Of Date)
    Public Property ohcon As Nullable(Of Integer)
    Public Property ohest As Nullable(Of Integer)
    Public Property ohfact As Nullable(Of Date)
    Public Property ohhact As String
    Public Property ohuact As String

End Class
