'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0023
    Public Property ojnumi As Integer
    Public Property ojtc1 As Nullable(Of Integer)
    Public Property ojtc4 As Nullable(Of Integer)
    Public Property ojcant As Nullable(Of Integer)
    Public Property ojest As Nullable(Of Integer)
    Public Property ojdif As Nullable(Of Boolean)
    Public Property ojto1 As Nullable(Of Integer)
    Public Property ojto2 As Nullable(Of Integer)
    Public Property ojfact As Nullable(Of Date)
    Public Property ojhact As String
    Public Property ojuact As String

End Class
