'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO0052
    Public Property onnumi As Integer
    Public Property onolnumi As Integer
    Public Property onestado As Integer
    Public Property onBanco As String
    Public Property onMoneda As String
    Public Property onNDepos As String
    Public Property onFecha As Date
    Public Property onMonto As Decimal

    Public Overridable Property TO005 As TO005

End Class
