'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TO001C
    Public Property oacnumi As Integer
    Public Property oacoanumi As Integer
    Public Property oaccbnumi As Integer
    Public Property oacnrofac As Nullable(Of Long)
    Public Property oacnconc As Nullable(Of Integer)
    Public Property oacfdoc As Date

End Class
