'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TP007
    Public Property pinumi As Integer
    Public Property picper As Nullable(Of Integer)
    Public Property pifdoc As Nullable(Of Date)
    Public Property piturno As Nullable(Of Integer)
    Public Property pifact As Nullable(Of Date)
    Public Property pihact As String
    Public Property piuact As String

End Class
