'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TP008
    Public Property pknumi As Integer
    Public Property pkper As Nullable(Of Integer)
    Public Property pkmes As Nullable(Of Integer)
    Public Property pkanio As Nullable(Of Integer)
    Public Property pkfact As Nullable(Of Date)
    Public Property pkhact As String
    Public Property pkuact As String

End Class
