'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TP004
    Public Property penumi As Integer
    Public Property pemeses As Nullable(Of Integer)
    Public Property pedias As Nullable(Of Integer)
    Public Property pefvig As Nullable(Of Date)
    Public Property petipo As Nullable(Of Boolean)
    Public Property pefact As Nullable(Of Date)
    Public Property pehact As String
    Public Property peuact As String

End Class
