'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TP0061
    Public Property phnumi As Integer
    Public Property phfsal As Nullable(Of Date)
    Public Property phfing As Nullable(Of Date)
    Public Property phdias As Nullable(Of Integer)

End Class
