'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TP003
    Public Property pdnumi As Integer
    Public Property pdmeses As Nullable(Of Integer)
    Public Property pdmonto As Nullable(Of Decimal)
    Public Property pdfact As Nullable(Of Date)
    Public Property pdhact As String
    Public Property pduact As String

End Class
