'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TP001
    Public Property panumi As Integer
    Public Property patipo As Nullable(Of Boolean)
    Public Property pavalor As Nullable(Of Decimal)
    Public Property pacper As Nullable(Of Integer)
    Public Property paobs As String
    Public Property pavenc As Nullable(Of Integer)
    Public Property pafvenc As Nullable(Of Date)
    Public Property pafact As Nullable(Of Date)
    Public Property pahact As String
    Public Property pauact As String

End Class
