'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TP0081
    Public Property plline As Integer
    Public Property plnumi As Nullable(Of Integer)
    Public Property plcon As Nullable(Of Integer)
    Public Property pldesc As String
    Public Property plmonto As Nullable(Of Decimal)
    Public Property plnumibd As Nullable(Of Integer)

End Class
