'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TP002
    Public Property pbnumi As Integer
    Public Property pbcper As Nullable(Of Integer)
    Public Property pbano As Nullable(Of Integer)
    Public Property pbmes As Nullable(Of Integer)
    Public Property pbfact As Nullable(Of Date)
    Public Property pbhact As String
    Public Property pbuact As String

End Class
