'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TPA001
    Public Property aanumi As Integer
    Public Property aanumipadre As Nullable(Of Integer)
    Public Property aafecha As Nullable(Of Date)
    Public Property aatipo As Nullable(Of Integer)
    Public Property aacodcliprov As Nullable(Of Integer)
    Public Property aanomcliprov As String
    Public Property aaemision As Nullable(Of Integer)
    Public Property aaestado As Nullable(Of Integer)
    Public Property aamontototal As Nullable(Of Decimal)
    Public Property aamoneda As Nullable(Of Integer)
    Public Property aatc As Nullable(Of Decimal)
    Public Property aanscf As Nullable(Of Decimal)
    Public Property aanumiasiento As Nullable(Of Integer)

End Class
