'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TV0013
    Public Property tenumi As Integer
    Public Property tefdoc As Nullable(Of Date)
    Public Property tety4vend As Nullable(Of Integer)
    Public Property teobs As String
    Public Property tefact As Nullable(Of Date)
    Public Property tehact As String
    Public Property teuact As String

End Class
