'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TV00121
    Public Property tdnumi As Integer
    Public Property tdtv12numi As Nullable(Of Integer)
    Public Property tdtv13numi As Nullable(Of Integer)
    Public Property tdnrodoc As String
    Public Property tdfechaPago As Nullable(Of Date)
    Public Property tdmonto As Nullable(Of Decimal)
    Public Property tdnrorecibo As String
    Public Property tdty3banco As Nullable(Of Integer)
    Public Property tdnrocheque As String
    Public Property tdfact As Nullable(Of Date)
    Public Property tdhact As String
    Public Property tduact As String

End Class
