'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TV001
    Public Property tanumi As Integer
    Public Property taalm As Nullable(Of Integer)
    Public Property tafdoc As Nullable(Of Date)
    Public Property taven As Nullable(Of Integer)
    Public Property tatven As Nullable(Of Integer)
    Public Property tafvcr As Nullable(Of Date)
    Public Property taclpr As Integer
    Public Property tamon As Nullable(Of Integer)
    Public Property taest As Nullable(Of Integer)
    Public Property tatotal As Nullable(Of Decimal)
    Public Property tafact As Nullable(Of Date)
    Public Property tahact As String
    Public Property tauact As String

End Class
