'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TV0011
    Public Property tbnumi As Integer
    Public Property tbtv1numi As Nullable(Of Integer)
    Public Property tbty5prod As Nullable(Of Integer)
    Public Property tbest As Nullable(Of Integer)
    Public Property tbcmin As Nullable(Of Decimal)
    Public Property tbumin As Nullable(Of Integer)
    Public Property tbpbas As Nullable(Of Decimal)
    Public Property tbptot As Nullable(Of Decimal)
    Public Property tbporc As Nullable(Of Decimal)
    Public Property tbdesc As Nullable(Of Decimal)
    Public Property tbtotdesc As Nullable(Of Decimal)
    Public Property tbobs As String
    Public Property tbpcos As Nullable(Of Decimal)
    Public Property tbptot2 As Nullable(Of Decimal)
    Public Property tbfact As Nullable(Of Date)
    Public Property tbhact As String
    Public Property tbuact As String

End Class
