'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_StockDisp
    Public Property iacprod As Nullable(Of Integer)
    Public Property iacant As Nullable(Of Decimal)
    Public Property Pedidos As Decimal
    Public Property Disponible As Nullable(Of Decimal)
    Public Property iaalm As Nullable(Of Integer)

End Class
