'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vista_promconsumo
    Public Property ccnumi As Integer
    Public Property ccdesc As String
    Public Property cczona As Nullable(Of Integer)
    Public Property cctelf1 As String
    Public Property ccdirec As String
    Public Property ccest As Nullable(Of Integer)
    Public Property ccprconsu As Nullable(Of Integer)
    Public Property fTentativa As Nullable(Of Date)

End Class
