'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_CajaDetalle
    Public Property oanumi As Integer
    Public Property oafdoc As Nullable(Of Date)
    Public Property oacnrofac As Nullable(Of Long)
    Public Property cliente As String
    Public Property oarepa As Nullable(Of Integer)
    Public Property oaest As Nullable(Of Integer)
    Public Property oaap As Nullable(Of Integer)
    Public Property oapg As Nullable(Of Integer)
    Public Property total As Nullable(Of Decimal)
    Public Property contado As Nullable(Of Decimal)
    Public Property credito As Decimal
    Public Property tcre As Integer
    Public Property estado As Integer

End Class
