'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_Clientes
    Public Property ccnumi As Integer
    Public Property ccdesc As String
    Public Property cctelf1 As String
    Public Property cctelf2 As String
    Public Property ccdirec As String
    Public Property cczona As Nullable(Of Integer)
    Public Property cedesc As String
    Public Property cccat As Nullable(Of Integer)
    Public Property cicod As String
    Public Property cidesc As String
    Public Property ccest As Nullable(Of Integer)

End Class
