'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_ClientesPendientesNota
    Public Property ccnumi As Nullable(Of Integer)
    Public Property ccdctnum As String
    Public Property ccdesc As String
    Public Property ccdirec As String
    Public Property zon As Nullable(Of Integer)
    Public Property nzon As String
    Public Property codP As String
    Public Property can As Nullable(Of Integer)
    Public Property tot As Nullable(Of Decimal)
    Public Property ped As Integer
    Public Property cacat As Nullable(Of Integer)

End Class
