'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_CuentasPagar_PagosRealizados
    Public Property cpaprov As Nullable(Of Integer)
    Public Property cmdesc As String
    Public Property cpanumi As Nullable(Of Integer)
    Public Property cpaobs As String
    Public Property cpafven As Nullable(Of Date)
    Public Property cpamonto As Nullable(Of Decimal)
    Public Property saldo As Nullable(Of Decimal)
    Public Property pagado As Nullable(Of Decimal)
    Public Property cpblin As Integer
    Public Property cpbmonto As Nullable(Of Decimal)
    Public Property cpbfdoc As Nullable(Of Date)
    Public Property mora As Nullable(Of Integer)

End Class
