'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_EntregaPedidos
    Public Property Nro As Nullable(Of Long)
    Public Property odrepa As Nullable(Of Integer)
    Public Property cbdesc As String
    Public Property Contado As Nullable(Of Decimal)
    Public Property Credito As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)
    Public Property oenumi As Integer
    Public Property odnota As Nullable(Of Integer)
    Public Property odfdoc As Nullable(Of Date)
    Public Property odtprod As Nullable(Of Integer)
    Public Property cadesc As String
    Public Property cadesc2 As String

End Class
