'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_EquiposPrestadoCliente
    Public Property codbd As Integer
    Public Property codigo As String
    Public Property contacto As String
    Public Property carrito As Nullable(Of Integer)
    Public Property botellone As Nullable(Of Integer)
    Public Property nombre As String
    Public Property direccion As String

End Class
