'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_DiferenciaPedidoNota
    Public Property numi As Integer
    Public Property fecha As Nullable(Of Date)
    Public Property ccli As Nullable(Of Integer)
    Public Property cpro As Nullable(Of Integer)
    Public Property npro As String
    Public Property pedido As Nullable(Of Integer)
    Public Property nota As Nullable(Of Integer)
    Public Property cped As Integer
    Public Property cnot As Nullable(Of Integer)
    Public Property dif As Nullable(Of Integer)
    Public Property hora As String
    Public Property usuario As String

End Class
