'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vr_go_reciboCliente
    Public Property oanumi As Integer
    Public Property oafdoc As Nullable(Of Date)
    Public Property cedesc As String
    Public Property oarepa As Nullable(Of Integer)
    Public Property cbdesc As String
    Public Property ccnumi As Integer
    Public Property cccod As String
    Public Property ccdesc As String
    Public Property obpcant As Nullable(Of Decimal)
    Public Property cadesc2 As String
    Public Property obpbase As Nullable(Of Decimal)
    Public Property obptot As Nullable(Of Decimal)
    Public Property cctelf1 As String
    Public Property ccdirec As String
    Public Property oaobs As String
    Public Property oaanumiprev As Nullable(Of Integer)
    Public Property cbdesc2 As String

End Class
