'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_ListarZona
    Public Property numi As Integer
    Public Property ccity As Nullable(Of Integer)
    Public Property ncity As String
    Public Property cprov As Nullable(Of Integer)
    Public Property nprov As String
    Public Property czona As Nullable(Of Integer)
    Public Property nzona As String
    Public Property color As String
    Public Property fact As Nullable(Of Date)
    Public Property hact As String
    Public Property uact As String

End Class
