'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GraficaVentasVs
    Public Property oanumi As Integer
    Public Property oafdoc As Nullable(Of Date)
    Public Property total As Nullable(Of Decimal)
    Public Property anio As Nullable(Of Integer)
    Public Property mes1 As Nullable(Of Integer)
    Public Property mes2 As String

End Class
