'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_PrestamoEquiposDetallado
    Public Property chnumi As Integer
    Public Property ccdesc As String
    Public Property chlin As Integer
    Public Property chfec As Nullable(Of Date)
    Public Property chcod As String
    Public Property chdesc As String
    Public Property chtmov As Nullable(Of Integer)
    Public Property cpdesc As String
    Public Property chnota As Nullable(Of Integer)
    Public Property chnrem As Nullable(Of Integer)
    Public Property cant As Nullable(Of Double)
    Public Property monto As Nullable(Of Double)
    Public Property cpmov As Nullable(Of Integer)
    Public Property cpmovcli As Nullable(Of Integer)

End Class
