'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_UltimaVentaCliente
    Public Property numi As Integer
    Public Property rsoc As String
    Public Property fultven As Nullable(Of Date)
    Public Property telf As String
    Public Property direc As String
    Public Property czona As Nullable(Of Integer)
    Public Property dpto As String
    Public Property prov As String
    Public Property zona As String
    Public Property est As Nullable(Of Integer)

End Class
