'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_EquipoPrestadoVsUltimaVenta
    Public Property numi As Integer
    Public Property desc As String
    Public Property fultven As Nullable(Of Date)
    Public Property telf As String
    Public Property dir As String
    Public Property saldo As Nullable(Of Double)
    Public Property cequi As String
    Public Property nequi As String
    Public Property czona As Nullable(Of Integer)
    Public Property dpto As String
    Public Property prov As String
    Public Property zona As String

End Class
