'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_DespachoXProducto
    Public Property oaccbnumi As Integer
    Public Property canumi As Integer
    Public Property cacod As String
    Public Property cadesc As String
    Public Property cadesc2 As String
    Public Property categoria As String
    Public Property obpcant As Nullable(Of Decimal)
    Public Property oacnconc As Nullable(Of Integer)
    Public Property oaest As Nullable(Of Integer)
    Public Property oaap As Nullable(Of Integer)
    Public Property oafdoc As Nullable(Of Date)
    Public Property caja As Nullable(Of Decimal)
    Public Property Unidad As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)

End Class
