'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_DespachoXCliente
    Public Property oaccbnumi As Integer
    Public Property ccnumi As Integer
    Public Property cccod As String
    Public Property ccdesc As String
    Public Property oacnrofact As Long
    Public Property obptot As Nullable(Of Decimal)
    Public Property obdesc As Nullable(Of Decimal)
    Public Property obtotal As Nullable(Of Decimal)
    Public Property IdZona As Nullable(Of Integer)
    Public Property oaest As Nullable(Of Integer)
    Public Property oaap As Nullable(Of Integer)
    Public Property oafdoc As Nullable(Of Date)
    Public Property oaobs As String
    Public Property oanumi As Integer

End Class
