'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_CajaGeneral
    Public Property IdCaja As Integer
    Public Property FechaCaja As Nullable(Of Date)
    Public Property Conciliacion As Nullable(Of Integer)
    Public Property FechaPedido As Nullable(Of Date)
    Public Property Repartidor As String
    Public Property TotalConciliacion As Nullable(Of Decimal)
    Public Property TotalEfectivo As Nullable(Of Decimal)
    Public Property TotalCredito As Nullable(Of Decimal)
    Public Property TotalDeposito As Nullable(Of Decimal)
    Public Property TotalGeneral As Nullable(Of Decimal)
    Public Property Diferencia As Nullable(Of Decimal)

End Class
