'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_GO_FacturaVsVenta2
    Public Property lin As Nullable(Of Integer)
    Public Property nota As Nullable(Of Integer)
    Public Property fecha As Nullable(Of Date)
    Public Property ccli As Nullable(Of Integer)
    Public Property ncli As String
    Public Property mefec As Nullable(Of Decimal)
    Public Property mcred As Nullable(Of Decimal)
    Public Property mfact As Nullable(Of Decimal)
    Public Property recibo As String
    Public Property factura As String
    Public Property tipo As String

End Class
