'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_KadexCliente
    Public Property tprod As Nullable(Of Integer)
    Public Property grupo As String
    Public Property nnota As Nullable(Of Integer)
    Public Property ccli As Nullable(Of Integer)
    Public Property nombre As String
    Public Property fecha As Nullable(Of Date)
    Public Property concepto As String
    Public Property con As Nullable(Of Decimal)
    Public Property cre As Nullable(Of Decimal)
    Public Property pago As Nullable(Of Decimal)
    Public Property saldo As Nullable(Of Decimal)
    Public Property nota As Nullable(Of Integer)
    Public Property tipo As String
    Public Property factura As Nullable(Of Integer)

End Class
