'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_LibroVentasChacaltaya2
    Public Property esp As Integer
    Public Property nro As Nullable(Of Long)
    Public Property fec As Nullable(Of Date)
    Public Property fac As String
    Public Property aut As Integer
    Public Property est As String
    Public Property nit As String
    Public Property nom As String
    Public Property nfac As String
    Public Property a As Nullable(Of Decimal)
    Public Property b As Nullable(Of Decimal)
    Public Property c As Nullable(Of Decimal)
    Public Property d As Nullable(Of Decimal)
    Public Property e As Nullable(Of Decimal)
    Public Property f As Nullable(Of Decimal)
    Public Property g As Nullable(Of Decimal)
    Public Property h As Nullable(Of Decimal)
    Public Property ccon As String

End Class
