'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_MO_GetPedidos
    Public Property oanumi As Integer
    Public Property oafdoc As Nullable(Of Date)
    Public Property oahora As String
    Public Property oaccli As Nullable(Of Integer)
    Public Property oazona As Nullable(Of Integer)
    Public Property oarepa As Nullable(Of Integer)
    Public Property oaobs As String
    Public Property oaobs2 As String
    Public Property oaest As Nullable(Of Integer)
    Public Property oaap As Nullable(Of Integer)
    Public Property oapg As Nullable(Of Integer)
    Public Property cceven As Nullable(Of Boolean)
    Public Property oafact As Nullable(Of Date)
    Public Property oahact As String
    Public Property oauact As String

End Class
