'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vr_Mam_ProductoVenta
    Public Property categoria As String
    Public Property numiProducto As Integer
    Public Property producto As String
    Public Property NombreCorto As String
    Public Property empresa As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property obpbase As Nullable(Of Decimal)
    Public Property TotalVenta As Nullable(Of Decimal)

End Class
