'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vr_Mam_Credito_Cliente
    Public Property pago As Decimal
    Public Property numicliente As Integer
    Public Property cliente As String
    Public Property direc As String
    Public Property telf1 As String
    Public Property contacto As String
    Public Property codven As Nullable(Of Integer)
    Public Property ydlcred As Integer
    Public Property tanumi As Integer
    Public Property tafdoc As Nullable(Of Date)
    Public Property tafvcr As Nullable(Of Date)
    Public Property yddias As Integer
    Public Property tatotal As Nullable(Of Decimal)
    Public Property desven As String
    Public Property TotCredit As Nullable(Of Decimal)
    Public Property pendiente As Nullable(Of Decimal)

End Class
