'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_Mam_Conciliacion
    Public Property canumi As Integer
    Public Property cadesc As String
    Public Property columna1 As Nullable(Of Integer)
    Public Property columna2 As Nullable(Of Integer)
    Public Property columna3 As Nullable(Of Integer)
    Public Property columna4 As Nullable(Of Integer)
    Public Property DEVOLUCION As Nullable(Of Integer)
    Public Property TOTAL As Nullable(Of Integer)

End Class
