'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_NotaCompra
    Public Property caanumi As Integer
    Public Property FechaCompra As String
    Public Property caaprov As Nullable(Of Integer)
    Public Property cmdesc As String
    Public Property cmrsocial As String
    Public Property cmnit As String
    Public Property cmtelf As String
    Public Property caanfac As String
    Public Property caatven As Nullable(Of Integer)
    Public Property tipocompra As String
    Public Property caafvcred As Nullable(Of Date)
    Public Property caadesc As Nullable(Of Decimal)
    Public Property caatotal As Nullable(Of Decimal)
    Public Property caaemision As Nullable(Of Integer)
    Public Property caaffactura As Nullable(Of Date)
    Public Property cabtc1numi As Nullable(Of Integer)
    Public Property cadesc As String
    Public Property cabcantcj As Nullable(Of Decimal)
    Public Property cabcantun As Nullable(Of Integer)
    Public Property cabpcomcj As Nullable(Of Decimal)
    Public Property cabpcomun As Nullable(Of Decimal)
    Public Property cabpcostocj As Nullable(Of Decimal)
    Public Property cabpcostoun As Nullable(Of Decimal)
    Public Property cabsubtot As Nullable(Of Decimal)
    Public Property cabdesccj As Nullable(Of Decimal)
    Public Property cabdescpro1cj As Nullable(Of Decimal)
    Public Property cabdescpro2cj As Nullable(Of Decimal)
    Public Property cabtot As Nullable(Of Decimal)
    Public Property fcarsocial As String
    Public Property fcanfac As Nullable(Of Long)
    Public Property fcaautoriz As Nullable(Of Long)
    Public Property fcaccont As String
    Public Property plazo As Nullable(Of Integer)

End Class
