'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_ProductosMesas
    Public Property canumi As Integer
    Public Property cadesc As String
    Public Property vend1 As Nullable(Of Decimal)
    Public Property totvend1 As Nullable(Of Decimal)
    Public Property vend2 As Nullable(Of Decimal)
    Public Property totvend2 As Nullable(Of Decimal)
    Public Property vend3 As Nullable(Of Decimal)
    Public Property totvend3 As Nullable(Of Decimal)
    Public Property vend4 As Nullable(Of Decimal)
    Public Property totvend4 As Nullable(Of Decimal)

End Class
