'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_ResumenNotas
    Public Property odnumi As Integer
    Public Property odnota As Nullable(Of Integer)
    Public Property odfdoc As Nullable(Of Date)
    Public Property contado As Nullable(Of Decimal)
    Public Property credito As Nullable(Of Decimal)
    Public Property equipos As Nullable(Of Double)
    Public Property pagos As Nullable(Of Decimal)
    Public Property total As Nullable(Of Double)

End Class
