'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_stockActual
    Public Property canumi As Integer
    Public Property cacod As String
    Public Property cadesc As String
    Public Property cadesc2 As String
    Public Property caest As Nullable(Of Boolean)
    Public Property iacprod As Nullable(Of Integer)
    Public Property iacant As Nullable(Of Decimal)
    Public Property caconv As Nullable(Of Decimal)
    Public Property cenum As Nullable(Of Boolean)
    Public Property cedesc As String

End Class
