'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_StockDisponible
    Public Property canumi As Integer
    Public Property cadesc As String
    Public Property categoria As String
    Public Property stockSinPedido As Decimal
    Public Property StockSoloPedidos As Decimal
    Public Property StockFinal As Nullable(Of Decimal)

End Class
