'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_UtilidadPorProducto
    Public Property canumi As Integer
    Public Property producto As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property precioCosto As Nullable(Of Decimal)
    Public Property precioVenta As Nullable(Of Decimal)
    Public Property Utilidad As Nullable(Of Decimal)

End Class
