'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vr_VentasVendidas
    Public Property aanumi As Integer
    Public Property aabdes As String
    Public Property ydnumi As Integer
    Public Property yddesc As String
    Public Property CodVenta As Integer
    Public Property cliente As String
    Public Property facturas As String
    Public Property FechaVenta As Nullable(Of Date)
    Public Property total As Nullable(Of Decimal)

End Class
