'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VR_VistaPedido_PrecioCosto
    Public Property oanumi As String
    Public Property oafdoc As Nullable(Of Date)
    Public Property codcliente As Integer
    Public Property cliente As String
    Public Property codRepartidor As Integer
    Public Property repartidor As String
    Public Property precioCosto As Nullable(Of Decimal)
    Public Property precioVenta As Nullable(Of Decimal)
    Public Property Utilidad As Nullable(Of Decimal)

End Class
