'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ZY0021
    Public Property ycline As Integer
    Public Property ycnumi As Nullable(Of Integer)
    Public Property ycyanumi As Nullable(Of Integer)
    Public Property ycshow As Nullable(Of Boolean)
    Public Property ycadd As Nullable(Of Boolean)
    Public Property ycmod As Nullable(Of Boolean)
    Public Property ycdel As Nullable(Of Boolean)

End Class
